apiVersion: v1
kind: Service
metadata:
  name: arks-gallery
spec:
  selector:
    app: arks-gallery
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
